### ISSUE TITLE
Homework 1

### ISSUE THREAD

**Issue by braemy** [lfaucon/ada-homeworks#2]
Hi I corrected you first homework.

Intro to pandas:
the ex 1 and 5 are well commented.

 There are less comment on your advanced exercice. It would be better to use different cells to show all your state and add some comment between them

You should also explain your assumption, for example why you replace all the NaN value by 0 or for example for Sierra Leone why you only consider the variable 'etc_new_deaths' and not 'death_confirmed'. I don't which one is right, but you should write an assumption.

Data wrangling: 
I think that ex01 is wrong, (t I don't solve it like that), but I understand what you tried to do
The advanced exercises is very good. You always wrote an assumption before and comment your result with a plot after, you have a good structure. Well done!

**Comment by cyril-p** [comment]
Hello,

Same comments as above. I also think that Data Wrangling/ ex1 is false, but Titanic exercise is very good!
