### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by CriMenghini** [lfaucon/ada-homeworks#8]
Hey guys!!

Comments:
The textual description is clear and understandable. It describes well the processes you did. 
The code is concise and pythonic (the next hw you can include more comments on it :) ). Due to these two things I suggest you to wrap some processes in functions for the tidiness of the notebook. 
You obtain as result what was required! (Maybe I would scale a bit more the colours for differentiating between the 4 cantons that get more money).

Overall: well done guyzzzzz

**Comment by lfaucon** [comment]
Thanks for the review
